// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO "chat_messages" (
  "exercise_uuid", 
  "user_uuid", 
  "role", 
  "content",
  "prompt_tokens",
  "completion_tokens"
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING uuid, ts, exercise_uuid, user_uuid, role, content, prompt_tokens, completion_tokens
`

type CreateChatMessageParams struct {
	ExerciseUuid     uuid.UUID `json:"exercise_uuid"`
	UserUuid         uuid.UUID `json:"user_uuid"`
	Role             string    `json:"role"`
	Content          string    `json:"content"`
	PromptTokens     int32     `json:"prompt_tokens"`
	CompletionTokens int32     `json:"completion_tokens"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ExerciseUuid,
		arg.UserUuid,
		arg.Role,
		arg.Content,
		arg.PromptTokens,
		arg.CompletionTokens,
	)
	var i ChatMessage
	err := row.Scan(
		&i.Uuid,
		&i.Ts,
		&i.ExerciseUuid,
		&i.UserUuid,
		&i.Role,
		&i.Content,
		&i.PromptTokens,
		&i.CompletionTokens,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT uuid, ts, exercise_uuid, user_uuid, role, content, prompt_tokens, completion_tokens FROM "chat_messages"
WHERE "exercise_uuid" = $1 AND "user_uuid" = $2
ORDER BY "ts" ASC
LIMIT $3 OFFSET $4
`

type ListChatMessagesParams struct {
	ExerciseUuid uuid.UUID `json:"exercise_uuid"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages,
		arg.ExerciseUuid,
		arg.UserUuid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.Uuid,
			&i.Ts,
			&i.ExerciseUuid,
			&i.UserUuid,
			&i.Role,
			&i.Content,
			&i.PromptTokens,
			&i.CompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
