// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_translations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCourseTranslation = `-- name: CreateCourseTranslation :one
INSERT INTO "course_translations" (
  "course_uuid",
  "language",
  "name",
  "description",
  "bullets"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING uuid, course_uuid, language, name, description, bullets
`

type CreateCourseTranslationParams struct {
	CourseUuid  uuid.UUID `json:"course_uuid"`
	Language    string    `json:"language"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Bullets     string    `json:"bullets"`
}

func (q *Queries) CreateCourseTranslation(ctx context.Context, arg CreateCourseTranslationParams) (CourseTranslation, error) {
	row := q.db.QueryRow(ctx, createCourseTranslation,
		arg.CourseUuid,
		arg.Language,
		arg.Name,
		arg.Description,
		arg.Bullets,
	)
	var i CourseTranslation
	err := row.Scan(
		&i.Uuid,
		&i.CourseUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Bullets,
	)
	return i, err
}

const deleteCourseTranslation = `-- name: DeleteCourseTranslation :exec
DELETE FROM "course_translations"
USING "courses"
WHERE "course_translations"."course_uuid" = "courses"."uuid"
AND "courses"."uuid" = $1
`

func (q *Queries) DeleteCourseTranslation(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseTranslation, argUuid)
	return err
}

const getCourseTranslation = `-- name: GetCourseTranslation :one
SELECT course_translations.uuid, course_uuid, language, name, description, bullets, courses.uuid, created_at, modified_at, deleted_at, subject, price, discount, is_active, difficulty FROM "course_translations"
JOIN "courses" ON "course_translations"."course_uuid" = "courses"."uuid"
WHERE "course_translations"."uuid" = $1
AND "courses"."deleted_at" IS NULL
LIMIT 1
`

type GetCourseTranslationRow struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CourseUuid  uuid.UUID  `json:"course_uuid"`
	Language    string     `json:"language"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Bullets     string     `json:"bullets"`
	Uuid_2      uuid.UUID  `json:"uuid_2"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	Subject     string     `json:"subject"`
	Price       int16      `json:"price"`
	Discount    int16      `json:"discount"`
	IsActive    bool       `json:"is_active"`
	Difficulty  int16      `json:"difficulty"`
}

func (q *Queries) GetCourseTranslation(ctx context.Context, argUuid uuid.UUID) (GetCourseTranslationRow, error) {
	row := q.db.QueryRow(ctx, getCourseTranslation, argUuid)
	var i GetCourseTranslationRow
	err := row.Scan(
		&i.Uuid,
		&i.CourseUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Bullets,
		&i.Uuid_2,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.Subject,
		&i.Price,
		&i.Discount,
		&i.IsActive,
		&i.Difficulty,
	)
	return i, err
}

const updateCourseTranslation = `-- name: UpdateCourseTranslation :one
UPDATE "course_translations"
SET "name" = COALESCE($3, "name"),
    "description" = COALESCE($4, "description"),
    "bullets" = COALESCE($5, "bullets")
FROM "courses"
WHERE "course_translations"."course_uuid" = "courses"."uuid"
AND "courses"."uuid" = $1 AND "course_translations"."language" = $2
RETURNING course_translations.uuid, course_translations.course_uuid, course_translations.language, course_translations.name, course_translations.description, course_translations.bullets
`

type UpdateCourseTranslationParams struct {
	Uuid        uuid.UUID `json:"uuid"`
	Language    string    `json:"language"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Bullets     *string   `json:"bullets"`
}

func (q *Queries) UpdateCourseTranslation(ctx context.Context, arg UpdateCourseTranslationParams) (CourseTranslation, error) {
	row := q.db.QueryRow(ctx, updateCourseTranslation,
		arg.Uuid,
		arg.Language,
		arg.Name,
		arg.Description,
		arg.Bullets,
	)
	var i CourseTranslation
	err := row.Scan(
		&i.Uuid,
		&i.CourseUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Bullets,
	)
	return i, err
}
