// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lesson_translations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLessonTranslation = `-- name: CreateLessonTranslation :one
INSERT INTO "lesson_translations" (
  "lesson_uuid",
  "language",
  "name",
  "description",
  "content"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING uuid, lesson_uuid, language, name, description, content
`

type CreateLessonTranslationParams struct {
	LessonUuid  uuid.UUID `json:"lesson_uuid"`
	Language    string    `json:"language"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Content     string    `json:"content"`
}

func (q *Queries) CreateLessonTranslation(ctx context.Context, arg CreateLessonTranslationParams) (LessonTranslation, error) {
	row := q.db.QueryRow(ctx, createLessonTranslation,
		arg.LessonUuid,
		arg.Language,
		arg.Name,
		arg.Description,
		arg.Content,
	)
	var i LessonTranslation
	err := row.Scan(
		&i.Uuid,
		&i.LessonUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Content,
	)
	return i, err
}

const deleteLessonTranslation = `-- name: DeleteLessonTranslation :exec
DELETE FROM "lesson_translations"
USING "lessons"
WHERE "lesson_translations"."lesson_uuid" = "lessons"."uuid"
AND "lessons"."uuid" = $1
`

func (q *Queries) DeleteLessonTranslation(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLessonTranslation, argUuid)
	return err
}

const getLessonTranslation = `-- name: GetLessonTranslation :one
SELECT lesson_translations.uuid, lesson_uuid, language, name, description, content, lessons.uuid, created_at, modified_at, deleted_at, course_uuid, order_index, is_public FROM "lesson_translations"
JOIN "lessons" ON "lesson_translations"."lesson_uuid" = "lessons"."uuid"
WHERE "lesson_translations"."uuid" = $1
AND "lessons"."deleted_at" IS NULL
LIMIT 1
`

type GetLessonTranslationRow struct {
	Uuid        uuid.UUID  `json:"uuid"`
	LessonUuid  uuid.UUID  `json:"lesson_uuid"`
	Language    string     `json:"language"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Content     string     `json:"content"`
	Uuid_2      uuid.UUID  `json:"uuid_2"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CourseUuid  uuid.UUID  `json:"course_uuid"`
	OrderIndex  int16      `json:"order_index"`
	IsPublic    bool       `json:"is_public"`
}

func (q *Queries) GetLessonTranslation(ctx context.Context, argUuid uuid.UUID) (GetLessonTranslationRow, error) {
	row := q.db.QueryRow(ctx, getLessonTranslation, argUuid)
	var i GetLessonTranslationRow
	err := row.Scan(
		&i.Uuid,
		&i.LessonUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.Uuid_2,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.CourseUuid,
		&i.OrderIndex,
		&i.IsPublic,
	)
	return i, err
}

const updateLessonTranslation = `-- name: UpdateLessonTranslation :one
UPDATE "lesson_translations"
SET "name" = COALESCE($3, "name"),
    "description" = COALESCE($4, "description"),
    "content" = COALESCE($5, "content")
FROM "lessons"
WHERE "lesson_translations"."lesson_uuid" = "lessons"."uuid" AND "lesson_translations"."language" = $2
AND "lessons"."uuid" = $1
RETURNING lesson_translations.uuid, lesson_translations.lesson_uuid, lesson_translations.language, lesson_translations.name, lesson_translations.description, lesson_translations.content
`

type UpdateLessonTranslationParams struct {
	Uuid        uuid.UUID `json:"uuid"`
	Language    string    `json:"language"`
	Name        *string   `json:"name"`
	Description *string   `json:"description"`
	Content     *string   `json:"content"`
}

func (q *Queries) UpdateLessonTranslation(ctx context.Context, arg UpdateLessonTranslationParams) (LessonTranslation, error) {
	row := q.db.QueryRow(ctx, updateLessonTranslation,
		arg.Uuid,
		arg.Language,
		arg.Name,
		arg.Description,
		arg.Content,
	)
	var i LessonTranslation
	err := row.Scan(
		&i.Uuid,
		&i.LessonUuid,
		&i.Language,
		&i.Name,
		&i.Description,
		&i.Content,
	)
	return i, err
}
