// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ExerciseType string

const (
	ExerciseTypeQuiz ExerciseType = "quiz"
	ExerciseTypeCode ExerciseType = "code"
)

func (e *ExerciseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExerciseType(s)
	case string:
		*e = ExerciseType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExerciseType: %T", src)
	}
	return nil
}

type NullExerciseType struct {
	ExerciseType ExerciseType `json:"exercise_type"`
	Valid        bool         `json:"valid"` // Valid is true if ExerciseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExerciseType) Scan(value interface{}) error {
	if value == nil {
		ns.ExerciseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExerciseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExerciseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExerciseType), nil
}

type Course struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Subject     string     `json:"subject"`
	Price       int16      `json:"price"`
	Discount    int16      `json:"discount"`
	IsActive    bool       `json:"is_active"`
	Difficulty  int16      `json:"difficulty"`
	Bullets     string     `json:"bullets"`
}

type Exercise struct {
	Uuid        uuid.UUID       `json:"uuid"`
	CreatedAt   time.Time       `json:"created_at"`
	ModifiedAt  time.Time       `json:"modified_at"`
	DeletedAt   *time.Time      `json:"deleted_at"`
	LessonUuid  uuid.UUID       `json:"lesson_uuid"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	OrderIndex  int16           `json:"order_index"`
	Reward      int16           `json:"reward"`
	Type        ExerciseType    `json:"type"`
	Data        json.RawMessage `json:"data"`
}

type Lesson struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CourseUuid  uuid.UUID  `json:"course_uuid"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	OrderIndex  int16      `json:"order_index"`
	IsPublic    bool       `json:"is_public"`
}

type User struct {
	Uuid         uuid.UUID  `json:"uuid"`
	CreatedAt    time.Time  `json:"created_at"`
	ModifiedAt   time.Time  `json:"modified_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	IsVerified   bool       `json:"is_verified"`
	Streak       int32      `json:"streak"`
	Score        int32      `json:"score"`
	IsAdmin      bool       `json:"is_admin"`
}

type UserCourse struct {
	Uuid           uuid.UUID  `json:"uuid"`
	StartedAt      time.Time  `json:"started_at"`
	LastAccessedAt *time.Time `json:"last_accessed_at"`
	UserUuid       uuid.UUID  `json:"user_uuid"`
	CourseUuid     uuid.UUID  `json:"course_uuid"`
	CompletedAt    *time.Time `json:"completed_at"`
}

type UserExercise struct {
	Uuid           uuid.UUID       `json:"uuid"`
	StartedAt      time.Time       `json:"started_at"`
	LastAccessedAt *time.Time      `json:"last_accessed_at"`
	UserUuid       uuid.UUID       `json:"user_uuid"`
	ExerciseUuid   uuid.UUID       `json:"exercise_uuid"`
	Submission     json.RawMessage `json:"submission"`
	Attempts       int32           `json:"attempts"`
	CompletedAt    *time.Time      `json:"completed_at"`
}

type UserLesson struct {
	Uuid           uuid.UUID  `json:"uuid"`
	StartedAt      time.Time  `json:"started_at"`
	LastAccessedAt *time.Time `json:"last_accessed_at"`
	UserUuid       uuid.UUID  `json:"user_uuid"`
	LessonUuid     uuid.UUID  `json:"lesson_uuid"`
	CompletedAt    *time.Time `json:"completed_at"`
}
