// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_lessons.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserLesson = `-- name: CreateUserLesson :one
INSERT INTO "user_lessons" (
  "user_uuid", 
  "lesson_uuid", 
  "completed_at"
) VALUES (
  $1, $2, $3
)
RETURNING uuid, started_at, last_accessed_at, user_uuid, lesson_uuid, completed_at
`

type CreateUserLessonParams struct {
	UserUuid    uuid.UUID  `json:"user_uuid"`
	LessonUuid  uuid.UUID  `json:"lesson_uuid"`
	CompletedAt *time.Time `json:"completed_at"`
}

func (q *Queries) CreateUserLesson(ctx context.Context, arg CreateUserLessonParams) (UserLesson, error) {
	row := q.db.QueryRow(ctx, createUserLesson, arg.UserUuid, arg.LessonUuid, arg.CompletedAt)
	var i UserLesson
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.LessonUuid,
		&i.CompletedAt,
	)
	return i, err
}

const deleteUserLesson = `-- name: DeleteUserLesson :exec
DELETE FROM "user_lessons"
WHERE "uuid" = $1
`

func (q *Queries) DeleteUserLesson(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserLesson, argUuid)
	return err
}

const getUserLesson = `-- name: GetUserLesson :one
SELECT uuid, started_at, last_accessed_at, user_uuid, lesson_uuid, completed_at FROM "user_lessons"
WHERE "uuid" = $1
LIMIT 1
`

func (q *Queries) GetUserLesson(ctx context.Context, argUuid uuid.UUID) (UserLesson, error) {
	row := q.db.QueryRow(ctx, getUserLesson, argUuid)
	var i UserLesson
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.LessonUuid,
		&i.CompletedAt,
	)
	return i, err
}

const getUserLessonByUserAndLesson = `-- name: GetUserLessonByUserAndLesson :one
SELECT uuid, started_at, last_accessed_at, user_uuid, lesson_uuid, completed_at FROM "user_lessons"
WHERE "user_uuid" = $1 AND "lesson_uuid" = $2
LIMIT 1
`

type GetUserLessonByUserAndLessonParams struct {
	UserUuid   uuid.UUID `json:"user_uuid"`
	LessonUuid uuid.UUID `json:"lesson_uuid"`
}

func (q *Queries) GetUserLessonByUserAndLesson(ctx context.Context, arg GetUserLessonByUserAndLessonParams) (UserLesson, error) {
	row := q.db.QueryRow(ctx, getUserLessonByUserAndLesson, arg.UserUuid, arg.LessonUuid)
	var i UserLesson
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.LessonUuid,
		&i.CompletedAt,
	)
	return i, err
}

const updateUserLesson = `-- name: UpdateUserLesson :one
UPDATE "user_lessons"
SET "user_uuid" = COALESCE($2, "user_uuid"), 
    "lesson_uuid" = COALESCE($3, "lesson_uuid"), 
    "completed_at" = COALESCE($4, "completed_at")
WHERE "uuid" = $1
RETURNING uuid, started_at, last_accessed_at, user_uuid, lesson_uuid, completed_at
`

type UpdateUserLessonParams struct {
	Uuid        uuid.UUID  `json:"uuid"`
	UserUuid    *uuid.UUID `json:"user_uuid"`
	LessonUuid  *uuid.UUID `json:"lesson_uuid"`
	CompletedAt *time.Time `json:"completed_at"`
}

func (q *Queries) UpdateUserLesson(ctx context.Context, arg UpdateUserLessonParams) (UserLesson, error) {
	row := q.db.QueryRow(ctx, updateUserLesson,
		arg.Uuid,
		arg.UserUuid,
		arg.LessonUuid,
		arg.CompletedAt,
	)
	var i UserLesson
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.LessonUuid,
		&i.CompletedAt,
	)
	return i, err
}
