// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM "users"
WHERE "deleted_at" IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "users" (
  "first_name", 
  "last_name", 
  "email",
  "password_hash",
  "is_verified",
  "is_admin"
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsVerified   bool   `json:"is_verified"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.IsVerified,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Streak,
		&i.Score,
		&i.IsAdmin,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE "users"
SET "deleted_at" = NOW()
WHERE "uuid" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, argUuid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin FROM "users"
WHERE "uuid" = $1 AND "deleted_at" IS NULL 
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, argUuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Streak,
		&i.Score,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin FROM "users"
WHERE "email" = $1 AND "deleted_at" IS NULL 
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Streak,
		&i.Score,
		&i.IsAdmin,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM "users"
WHERE "uuid" = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, argUuid)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin FROM "users"
WHERE "deleted_at" IS NULL
ORDER BY "created_at" DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.DeletedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.IsVerified,
			&i.Streak,
			&i.Score,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeleteUser = `-- name: UndeleteUser :exec
UPDATE "users"
SET "deleted_at" = NULL
WHERE "uuid" = $1
`

func (q *Queries) UndeleteUser(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, undeleteUser, argUuid)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET "first_name" = COALESCE($2, "first_name"), 
    "last_name" = COALESCE($3, "last_name"), 
    "email" = COALESCE($4, "email"), 
    "is_verified" = COALESCE($5, "is_verified"), 
    "is_admin" = COALESCE($6, "is_admin"),
    "modified_at" = NOW()
WHERE "uuid" = $1
RETURNING uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin
`

type UpdateUserParams struct {
	Uuid       uuid.UUID `json:"uuid"`
	FirstName  *string   `json:"first_name"`
	LastName   *string   `json:"last_name"`
	Email      *string   `json:"email"`
	IsVerified *bool     `json:"is_verified"`
	IsAdmin    *bool     `json:"is_admin"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Uuid,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.IsVerified,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Streak,
		&i.Score,
		&i.IsAdmin,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE "users"
SET "password_hash" = $2,
    "modified_at" = NOW()
WHERE "uuid" = $1
RETURNING uuid, created_at, modified_at, deleted_at, first_name, last_name, email, password_hash, is_verified, streak, score, is_admin
`

type UpdateUserPasswordParams struct {
	Uuid         uuid.UUID `json:"uuid"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.Uuid, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.DeletedAt,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.Streak,
		&i.Score,
		&i.IsAdmin,
	)
	return i, err
}
