// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_exercises.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const completeUserExercise = `-- name: CompleteUserExercise :one
UPDATE "user_exercises"
SET "completed_at" = NOW()
WHERE "user_uuid" = $1 AND "exercise_uuid" = $2
RETURNING uuid, started_at, last_accessed_at, user_uuid, exercise_uuid, submission, attempts, completed_at
`

type CompleteUserExerciseParams struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	ExerciseUuid uuid.UUID `json:"exercise_uuid"`
}

func (q *Queries) CompleteUserExercise(ctx context.Context, arg CompleteUserExerciseParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, completeUserExercise, arg.UserUuid, arg.ExerciseUuid)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const createUserExercise = `-- name: CreateUserExercise :one
INSERT INTO "user_exercises" (
  "user_uuid", 
  "exercise_uuid", 
  "submission",
  "attempts",
  "completed_at"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING uuid, started_at, last_accessed_at, user_uuid, exercise_uuid, submission, attempts, completed_at
`

type CreateUserExerciseParams struct {
	UserUuid     uuid.UUID       `json:"user_uuid"`
	ExerciseUuid uuid.UUID       `json:"exercise_uuid"`
	Submission   json.RawMessage `json:"submission"`
	Attempts     int32           `json:"attempts"`
	CompletedAt  *time.Time      `json:"completed_at"`
}

func (q *Queries) CreateUserExercise(ctx context.Context, arg CreateUserExerciseParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, createUserExercise,
		arg.UserUuid,
		arg.ExerciseUuid,
		arg.Submission,
		arg.Attempts,
		arg.CompletedAt,
	)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const getUserExercise = `-- name: GetUserExercise :one
SELECT uuid, started_at, last_accessed_at, user_uuid, exercise_uuid, submission, attempts, completed_at FROM "user_exercises"
WHERE "user_uuid" = $1 AND "exercise_uuid" = $2
LIMIT 1
`

type GetUserExerciseParams struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	ExerciseUuid uuid.UUID `json:"exercise_uuid"`
}

func (q *Queries) GetUserExercise(ctx context.Context, arg GetUserExerciseParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, getUserExercise, arg.UserUuid, arg.ExerciseUuid)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const resetUserExercise = `-- name: ResetUserExercise :one
UPDATE "user_exercises"
SET "submission" = '{}'::jsonb,
    "attempts" = 0,
    "completed_at" = NULL,
    "last_accessed_at" = NOW()
WHERE "user_uuid" = $1 AND "exercise_uuid" = $2
RETURNING uuid, started_at, last_accessed_at, user_uuid, exercise_uuid, submission, attempts, completed_at
`

type ResetUserExerciseParams struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	ExerciseUuid uuid.UUID `json:"exercise_uuid"`
}

func (q *Queries) ResetUserExercise(ctx context.Context, arg ResetUserExerciseParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, resetUserExercise, arg.UserUuid, arg.ExerciseUuid)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const updateUserExerciseSubmission = `-- name: UpdateUserExerciseSubmission :one
UPDATE "user_exercises"
SET "submission" = COALESCE($4, "submission"),
    "last_accessed_at" = NOW()
FROM "exercises"
WHERE "user_uuid" = $1 
AND "exercise_uuid" = $2 
AND "exercises"."type" = $3 
AND "exercises"."uuid" = "user_exercises"."exercise_uuid"
RETURNING user_exercises.uuid, user_exercises.started_at, user_exercises.last_accessed_at, user_exercises.user_uuid, user_exercises.exercise_uuid, user_exercises.submission, user_exercises.attempts, user_exercises.completed_at
`

type UpdateUserExerciseSubmissionParams struct {
	UserUuid     uuid.UUID        `json:"user_uuid"`
	ExerciseUuid uuid.UUID        `json:"exercise_uuid"`
	Type         ExerciseType     `json:"type"`
	Submission   *json.RawMessage `json:"submission"`
}

func (q *Queries) UpdateUserExerciseSubmission(ctx context.Context, arg UpdateUserExerciseSubmissionParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, updateUserExerciseSubmission,
		arg.UserUuid,
		arg.ExerciseUuid,
		arg.Type,
		arg.Submission,
	)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const updateUserExerciseSubmissionWithAttempts = `-- name: UpdateUserExerciseSubmissionWithAttempts :one
UPDATE "user_exercises"
SET "submission" = COALESCE($3, "submission"),
    "attempts" = "attempts" + 1,
    "last_accessed_at" = NOW()
WHERE "user_uuid" = $1 AND "exercise_uuid" = $2
RETURNING uuid, started_at, last_accessed_at, user_uuid, exercise_uuid, submission, attempts, completed_at
`

type UpdateUserExerciseSubmissionWithAttemptsParams struct {
	UserUuid     uuid.UUID        `json:"user_uuid"`
	ExerciseUuid uuid.UUID        `json:"exercise_uuid"`
	Submission   *json.RawMessage `json:"submission"`
}

func (q *Queries) UpdateUserExerciseSubmissionWithAttempts(ctx context.Context, arg UpdateUserExerciseSubmissionWithAttemptsParams) (UserExercise, error) {
	row := q.db.QueryRow(ctx, updateUserExerciseSubmissionWithAttempts, arg.UserUuid, arg.ExerciseUuid, arg.Submission)
	var i UserExercise
	err := row.Scan(
		&i.Uuid,
		&i.StartedAt,
		&i.LastAccessedAt,
		&i.UserUuid,
		&i.ExerciseUuid,
		&i.Submission,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}
