// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Subject     string     `json:"subject"`
	Price       int16      `json:"price"`
	Discount    int16      `json:"discount"`
	IsActive    bool       `json:"is_active"`
	Difficulty  int16      `json:"difficulty"`
	Bullets     string     `json:"bullets"`
}

type Exercise struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	LessonUuid  uuid.UUID  `json:"lesson_uuid"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	OrderIndex  int16      `json:"order_index"`
	Reward      int16      `json:"reward"`
	Data        []byte     `json:"data"`
}

type Lesson struct {
	Uuid        uuid.UUID  `json:"uuid"`
	CreatedAt   time.Time  `json:"created_at"`
	ModifiedAt  time.Time  `json:"modified_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CourseUuid  uuid.UUID  `json:"course_uuid"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	OrderIndex  int16      `json:"order_index"`
	IsPublic    bool       `json:"is_public"`
}

type User struct {
	Uuid         uuid.UUID  `json:"uuid"`
	CreatedAt    time.Time  `json:"created_at"`
	ModifiedAt   time.Time  `json:"modified_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	FirstName    string     `json:"first_name"`
	LastName     string     `json:"last_name"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	IsVerified   bool       `json:"is_verified"`
	Streak       int32      `json:"streak"`
	Score        int32      `json:"score"`
	IsAdmin      bool       `json:"is_admin"`
}
