// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, argUuid uuid.UUID) error
	GetUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	HardDeleteUser(ctx context.Context, argUuid uuid.UUID) error
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UndeleteUser(ctx context.Context, argUuid uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
