overrides:
  '@orval/core@<7.19.0': '>=7.19.0'
  '@orval/mcp@<7.18.0': '>=7.18.0'
  '@orval/mock@<7.20.0': '>=7.20.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
  react-router@>=7.0.0 <=7.11.0: '>=7.12.0'
